# Generated by Django 3.0.4 on 2020-03-27 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dog_gardens', '0002_doggarden_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='doggarden',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
