# Generated by Django 3.0.4 on 2020-03-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_gardens', '0003_doggarden_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='doggarden',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
